import { useState, useEffect, useCallback, useRef } from "react";
import { Link2, Copy, Check, Loader2, RefreshCw, Key, ExternalLink } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useToast } from "@/hooks/use-toast";
import { supabase } from "@/integrations/supabase/client";
import { useFounderAuth } from "@/contexts/FounderAuthContext";
import { useRounds } from "@/hooks/useRounds";
import { useQuery } from "@tanstack/react-query";
import { useNavigate } from "react-router-dom";
import { StatusLine, StatusState } from "./StatusLine";

interface ShareLinksCardProps {
  roundId?: string;
  roundSlug?: string;
}

interface InvestorLink {
  investorId: string;
  investorName: string;
  investorSlug: string;
  accessKey: string;
  url: string;
  status: string;
}

export function ShareLinksCard({ roundId, roundSlug }: ShareLinksCardProps) {
  const { user, profile } = useFounderAuth();
  const { toast } = useToast();
  const { openRound } = useRounds();
  const navigate = useNavigate();
  
  const [isGenerating, setIsGenerating] = useState(false);
  const [copiedItem, setCopiedItem] = useState<string | null>(null);
  const [status, setStatus] = useState<StatusState>("idle");
  const hasAutoGenerated = useRef(false);

  const effectiveRoundId = roundId || openRound?.id;
  const effectiveRoundSlug = roundSlug || openRound?.slug;
  const companySlug = profile?.company_slug;

  // Fetch all investors for this workspace (exclude 'lost' status)
  const { data: investors = [], isLoading: isLoadingInvestors } = useQuery({
    queryKey: ["investors", user?.id],
    queryFn: async () => {
      if (!user?.id) return [];
      
      const { data, error } = await supabase
        .from("investors")
        .select("id, name, slug, status")
        .eq("workspace_id", user.id)
        .neq("status", "lost")
        .order("name");

      if (error) throw error;
      return data;
    },
    enabled: !!user?.id,
  });

  // Fetch existing access keys for memo tool (including voided)
  const { data: existingKeys = [], isLoading: isLoadingKeys, refetch: refetchKeys } = useQuery({
    queryKey: ["memo-access-keys", effectiveRoundId],
    queryFn: async () => {
      if (!effectiveRoundId) return [];
      
      const { data, error } = await supabase
        .from("access_keys")
        .select("id, key, investor_id, status")
        .eq("round_id", effectiveRoundId)
        .eq("tool", "memo")
        .not("investor_id", "is", null);

      if (error) throw error;
      return data;
    },
    enabled: !!effectiveRoundId,
  });

  // Build investor links from existing active keys only
  const activeLinks = (() => {
    if (!investors.length || !companySlug || !effectiveRoundSlug) {
      return [] as InvestorLink[];
    }

    const active: InvestorLink[] = [];
    
    for (const investor of investors) {
      // Only show active keys (exclude voided)
      const existingKey = existingKeys.find(k => k.investor_id === investor.id && k.status === 'active');
      if (existingKey) {
        active.push({
          investorId: investor.id,
          investorName: investor.name,
          investorSlug: investor.slug,
          accessKey: existingKey.key,
          url: `${window.location.origin}/share/${companySlug}/${effectiveRoundSlug}/memo/${investor.slug}`,
          status: existingKey.status,
        });
      }
    }

    return active;
  })();

  // Generate links for investors who don't have them yet
  const generateNewLinks = useCallback(async () => {
    if (!effectiveRoundId || !investors.length || isGenerating) return;
    
    const investorsNeedingKeys = investors.filter(
      inv => !existingKeys.some(k => k.investor_id === inv.id)
    );

    if (investorsNeedingKeys.length === 0) {
      toast({ title: "All investors already have links" });
      return;
    }

    setIsGenerating(true);
    setStatus("loading");

    try {
      for (const investor of investorsNeedingKeys) {
        await supabase.functions.invoke("generate-access-key", {
          body: {
            roundId: effectiveRoundId,
            tool: "memo",
            investorId: investor.id,
          },
        });
      }

      // Refetch keys after all generations complete
      await refetchKeys();
      
      toast({ title: `Generated ${investorsNeedingKeys.length} new link(s)` });
      setStatus("success");
      setTimeout(() => setStatus("idle"), 3000);
    } catch (error) {
      console.error("Generate links error:", error);
      toast({
        title: "Failed to generate links",
        variant: "destructive",
      });
      setStatus("error");
      setTimeout(() => setStatus("idle"), 3000);
    } finally {
      setIsGenerating(false);
    }
  }, [effectiveRoundId, investors, existingKeys, isGenerating, refetchKeys, toast]);

  // Auto-generate on mount if there are investors without keys (only once)
  useEffect(() => {
    if (
      !isLoadingInvestors && 
      !isLoadingKeys && 
      investors.length > 0 && 
      effectiveRoundId &&
      !hasAutoGenerated.current
    ) {
      const investorsNeedingKeys = investors.filter(
        inv => !existingKeys.some(k => k.investor_id === inv.id)
      );
      
      if (investorsNeedingKeys.length > 0) {
        hasAutoGenerated.current = true;
        generateNewLinks();
      }
    }
  }, [isLoadingInvestors, isLoadingKeys, investors, existingKeys, effectiveRoundId, generateNewLinks]);

  const copyToClipboard = async (text: string, label: string, investorName: string) => {
    await navigator.clipboard.writeText(text);
    setCopiedItem(`${investorName}-${label}`);
    setTimeout(() => setCopiedItem(null), 2000);
    toast({ title: `${label} for ${investorName} copied` });
  };

  const handleNavigateToInvestor = (investorSlug: string) => {
    if (effectiveRoundSlug) {
      navigate(`/${effectiveRoundSlug}/memo/${investorSlug}`);
    }
  };

  if (!openRound) {
    return (
      <>
        <div className="rounded-xl border border-border bg-transparent overflow-hidden">
          <div className="px-4 py-3 border-b border-border flex items-center gap-2">
            <Link2 className="w-4 h-4 text-foreground" />
            <span className="text-sm font-medium">Share Links</span>
          </div>
          <div className="p-4">
            <p className="text-sm text-muted-foreground text-center py-4">
              Open a round first to share
            </p>
          </div>
        </div>
        <StatusLine status="idle" idleText="No active round" />
      </>
    );
  }

  const isLoading = isLoadingInvestors || isLoadingKeys;

  // Render a link row
  const renderLinkRow = (link: InvestorLink) => (
    <div
      key={link.investorId}
      onClick={() => handleNavigateToInvestor(link.investorSlug)}
      className="flex items-center justify-between px-3 py-2 rounded-lg border border-border cursor-pointer transition-colors bg-transparent hover:bg-secondary/50"
    >
      {/* Investor name */}
      <span className="text-sm font-medium">
        {link.investorName}
      </span>
      
      {/* Icons on right */}
      <div className="flex items-center gap-2">
        {/* Key icon + copy button */}
        <div className="flex items-center gap-0.5">
          <Key className="w-3 h-3 text-muted-foreground" />
          <Button
            size="sm"
            variant="ghost"
            onClick={(e) => {
              e.stopPropagation();
              copyToClipboard(link.accessKey, "Key", link.investorName);
            }}
            className="h-6 w-6 p-0 text-foreground hover:bg-accent hover:text-accent-foreground"
          >
            {copiedItem === `${link.investorName}-Key` ? (
              <Check className="w-3 h-3 text-green-600" />
            ) : (
              <Copy className="w-3 h-3" />
            )}
          </Button>
        </div>
        
        {/* Link icon + open button */}
        <div className="flex items-center gap-0.5">
          <Link2 className="w-3 h-3 text-muted-foreground" />
          <Button
            size="sm"
            variant="ghost"
            onClick={(e) => {
              e.stopPropagation();
              window.open(link.url, "_blank");
            }}
            className="h-6 w-6 p-0 text-foreground hover:bg-accent hover:text-accent-foreground"
          >
            <ExternalLink className="w-3 h-3" />
          </Button>
        </div>
      </div>
    </div>
  );

  return (
    <>
      <div className="rounded-xl border border-border bg-transparent overflow-hidden">
        <div className="px-4 py-3 border-b border-border flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Link2 className="w-4 h-4 text-foreground" />
            <span className="text-sm font-medium">Share Links</span>
          </div>
          <Button
            size="sm"
            variant="ghost"
            onClick={generateNewLinks}
            disabled={isLoading || isGenerating}
            className="h-7 px-2"
          >
            {isGenerating ? (
              <Loader2 className="w-3.5 h-3.5 animate-spin" />
            ) : (
              <RefreshCw className="w-3.5 h-3.5" />
            )}
          </Button>
        </div>
        
        <div className="p-4">
          {(isLoading || isGenerating) && activeLinks.length === 0 ? (
            <div className="flex items-center justify-center py-6 gap-2 text-sm text-muted-foreground">
              <Loader2 className="w-4 h-4 animate-spin" />
              <span>{isGenerating ? "Generating links..." : "Loading..."}</span>
            </div>
          ) : investors.length === 0 ? (
            <p className="text-sm text-muted-foreground text-center py-4">
              No investors in pipeline yet
            </p>
          ) : activeLinks.length === 0 && !isGenerating ? (
            <div className="text-center py-4">
              <p className="text-sm text-muted-foreground mb-3">
                {investors.length} investor(s) need links
              </p>
              <Button size="sm" onClick={generateNewLinks} disabled={isGenerating}>
                Generate Links
              </Button>
            </div>
          ) : (
            <div className="space-y-2">
              {activeLinks.map((link) => renderLinkRow(link))}
            </div>
          )}
        </div>
      </div>
      
      {/* Status Line - Outside Card */}
      <StatusLine 
        status={status}
        idleText={activeLinks.length > 0 ? `${activeLinks.length} active link(s)` : "Add investors to generate links"}
        loadingText="Generating links..."
        successText="Links generated successfully"
        errorText="Failed to generate links"
      />
    </>
  );
}
