project_id = "kruktizdznznouaorkej"

[functions.validate-access-key]
verify_jwt = false

[functions.check-user-exists]
verify_jwt = false

[functions.circuit-action]
verify_jwt = false

[functions.draft-memo-ai]
verify_jwt = true

[functions.generate-safe-document]
verify_jwt = false

[functions.log-investor-activity]
verify_jwt = false
